### ISSUE TITLE
fbrc.py won't open (HELP PLEASE)

### ISSUE THREAD

**Issue by zSilver98** [e2002e/fbrc#1]
Hi
fbrc.py won't open

└──╼ $python2 fbrc.py
Traceback (most recent call last):
  File "fbrc.py", line 4, in <module>
    import numba
ImportError: No module named numba

What should I do?
Thanks.

**Comment by e2002e** [comment]
The traceback gives us the instruction where the error occurs which is at `import numba`, and it's specified (through an exception named `importError`) that there is no modules named numba.
You need to install it but you can also replace `numba.prange()` by a normal `range()` in the code, and not import it.
Installing:
if you'r on linux you need to have pip2 `apt install python2-pip`
then pip2 install numba
On windows I guess you can install pip2 from the website or it's allready installed, you tell me.

Ps: it's psecified in the README that you need to do pip install numba,urllib,httplib
I've modified it so that it's pip2
